apiVersion: v1
kind: Service
metadata:
  name: {{ template "datastore.fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 8 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if ((index .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    product: {{ template "datastore.name" . }}  
  ports:
    {{ if or (eq .Values.datastore.serverMode "PLAIN") (eq .Values.datastore.serverMode "AUTOTLS") }} # AUTOTLS mode requires additional port for communicating with LetsEncrypt
    - protocol: TCP
      port: .Values.datastore.letsEncryptServicePort
      targetPort: .Values.datastore.letsEncryptContainerlPort
      name: {{ printf "%s-lets-encrypt" (include "datastore.name" .) }}
    - protocol: TCP
      port: .Values.datastore.dopServicePort
      targetPort: .Values.datastore.dopContainerlPort
      name: {{ printf "%s-main" (include "datastore.name" .) }}
