apiVersion: rookout.rookout.com/v1alpha1
kind: Rookout
metadata:
  name: rookout-sample
  labels:
    app: {{ template "operator.name" . }}
    chart: {{ template "operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rookout_env_vars:
    - name: "ROOKOUT_TOKEN"
      value: {{ .Values.operator.token | quote }}

  {{- if .Values.operator.matchers }}
  matchers:
  {{- range .Values.operator.matchers }}
    - deployment: {{ .deployment | quote }}
      {{- if .container }}
      container: {{ .container | quote }}
      {{- end}}
  {{- end }}

  {{- end }}
