apiVersion: rookout.rookout.com/v1alpha1
kind: Rookout
metadata:
  name: rookout-operator-configuration
  labels:
    app: {{ template "operator.name" . }}
    chart: {{ template "operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  matchers:
  {{- range .Values.operator.matchers }}
    - deployment: {{ .deployment | quote }}
      {{- if .container }}
      container: {{ .container | quote }}
      {{- end}}
      env_vars:
      {{- range .env_vars }}
        - name: {{ .name }}
          value: {{ .value}}
      {{- end}}
  {{- end}}
