apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app: {{ template "operator.name" . }}
    chart: {{ template "operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: rookout-controller-manager-metrics-service
  namespace: rookout
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    control-plane: controller-manager
---