image:
  repository: "us.gcr.io/rookout/rookout-k8s-operator"
  tag: "1.0"
  pullPolicy: Always

operator:
  matchers: # place your own matchers here
  resources:
    requests:
      cpu: 30m
      memory: 32Mi
    limits:
      cpu: 4000m
      memory: 1024Mi