image:
  repository: "rookout/k8s-operator"
  tag: "1.0"
  pullPolicy: "Always"

operator:
  init_container:
    image: "rookout/k8s-operator-init-container"
    tag: "1.0"

  resources:
    requests:
      cpu: 30m
      memory: 32Mi
    limits:
      cpu: 4000m
      memory: 1024Mi