image:
  repository: "rookout/k8s-operator"
  tag: "1.0"
  pullPolicy: "Always"

operator:
  matchers:
    - deployment: "test_deployment"
      container: "test_container"
      labels:
        - env: "test_env"
      env_vars:
        - name: "ROOKOUT_TOKEN"
          value: "<YOUR TOKEN>"

  init_container:
    image: "rookout/k8s-operator-init-container"
    tag: "1.0"

  resources:
    requests:
      cpu: 30m
      memory: 32Mi
    limits:
      cpu: 4000m
      memory: 1024Mi