image:
  repository: "gcr.io/rookoutdev/operator-test"
  tag: "latest"
  pullPolicy: "Always"

operator:
  matchers:
    - deployment: "java-one"
      container: ""
      env_vars:
        - name: "ROOKOUT_TOKEN"
          value: "2d1c78743eb256e80a4b4b53314c806253e88a17ae65044ce9818e3d294be2f0"
    # - deployment: "java-two"
    #   container: ""
    #   env_vars:
    #     - name: "ROOKOUT_TOKEN"
    #       value: "2d1c78743eb256e80a4b4b53314c806253e88a17ae65044ce9818e3d294be2f0"
    - deployment: "java-three"
      container: ""
      env_vars:
        - name: "ROOKOUT_TOKEN"
          value: "2d1c78743eb256e80a4b4b53314c806253e88a17ae65044ce9818e3d294be2f0"

  init_container:
    image: "rookout/k8s-operator-init-container"
    tag: "latest"

  resources:
    requests:
      cpu: 30m
      memory: 32Mi
    limits:
      cpu: 4000m
      memory: 1024Mi