image:
  repository: "us.gcr.io/rookout/rookout-k8s-operator"
  tag: "1.0"
  pullPolicy: Always

operator:
  token: "<YOUR ROOKOUT TOKEN>"
  matchers:
    - deployment : "example_deployment_matcher"
      container: "example_container_matcher"
      labelels:
        - name: "deployment label name"
          value: "deployment label value"

  resources:
    requests:
      cpu: 30m
      memory: 32Mi
    limits:
      cpu: 4000m
      memory: 1024Mi