rookout:
  
  # Set this to your Rookout organization token
  token: "0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF"

datastore:
  ingress:
    enabled: true
    tls:
      - hosts:
      
        # Set this to the domain name of the Datastore endpoint
        - datastore.yourcompany.com
        
        # Set this to the Let's Encrypt secret name
        secretName: my-lets-encrypt-secret
    hosts:
      
      # Set this to the domain name of the Datastore endpoint
      - host: datastore.yourcompany.com
        paths:
          - path: /
            pathType: Prefix
    annotations: 
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/ssl-redirect: 'true'
      
      # Set this to the name of the cert-manager Let's Encrypt cluster issuer
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      
      # If you are using an `Issuer` instead of a `ClusterIssuer`, change the line above to:
      # cert-manager.io/issuer: ...
