{{- if .Values.controller.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "controller.fullname" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
    {{- with .Values.controller.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.controller.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: 7488
      protocol: TCP
    {{- if eq .Values.controller.service.type "NodePort" }}
      nodePort: {{ .Values.controller.service.nodePort }}
    {{- end }}
  selector:
    {{- include "controller.selectorLabels" . | nindent 4 }}
{{- end }}