{{- if .Values.datastore.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datastore.fullname" . }}
  labels:
    {{- include "datastore.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      {{- include "datastore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.datastore.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "datastore.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "datastore.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.datastore.podSecurityContext | nindent 8 }}
      volumes:
      {{- if (eq (required "rookout.serverMode is required" .Values.rookout.serverMode) "TLS") }}
      - name: tls-secret
        secret:
          secretName: {{ required "In TLS mode, secretName holding key must be specified in rookout.datastoreTLSSecretName." .Values.rookout.datastoreTLSSecretName  }}
          items:
          - key: tls.key
            path: key.pem
          - key: tls.crt
            path: cert.pem
      {{- end }}
      {{ if not .Values.datastore.inMemoryDb }}
      - name: rookout-volume
        persistentVolumeClaim:
          claimName: rookout-data-on-prem-pvc
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.datastore.securityContext | nindent 12 }}
          image: "{{ .Values.datastore.image.repository }}/{{ .Values.datastore.image.name }}:{{ .Values.datastore.image.tag  }}"
          imagePullPolicy: {{ .Values.datastore.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 4009
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4009
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.datastore.resources | nindent 12 }}
          env:
            - name: ROOKOUT_DOP_LOGGING_TOKEN
              value: {{ .Values.rookout.token }}
            - name: ROOKOUT_DOP_SERVER_MODE
              value: {{ required "rookout.serverMode is required" .Values.rookout.serverMode | quote }}
            - name: ROOKOUT_DOP_PORT
              value: "8080"
            - name: ROOKOUT_DOP_IN_MEMORY_DB
              {{ if (.Values.datastore.inMemoryDb) }}
              value: "True"
              {{ else }}
              value: "False"
              {{ end }}
{{- with .Values.datastore.extraEnv }}
{{- toYaml . | nindent 12 }}
{{- end }}
          volumeMounts:
          {{ if not .Values.datastore.inMemoryDb }}
          - mountPath: "/var/rookout/database/db"
            name: rookout-volume
          {{ end }}
{{ if (eq (required "rookout.serverMode is required" .Values.rookout.serverMode) "TLS") }}
          - mountPath: /var/rookout
            name: tls-secret
            readOnly: true
{{ end }}
      {{- with .Values.datastore.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.datastore.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.datastore.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

