{{- if .Values.datastore.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "datastore.fullname" . }}
  labels:
    {{- include "datastore.labels" . | nindent 4 }}
    {{- with .Values.datastore.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.datastore.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.datastore.service.type }}
  ports:
    - port: {{ .Values.datastore.service.port }}
      targetPort: 8080
      protocol: TCP
    {{- if eq .Values.datastore.service.type "NodePort" }}
      nodePort: {{ .Values.datastore.service.nodePort }}
    {{- end }}
  selector:
    {{- include "datastore.selectorLabels" . | nindent 4 }}
{{- end }}