{{- if and .Values.token (not .Values.tokenExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rookout.tokenSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include .Chart.Name . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  token: {{ .Values.token | b64enc | quote }}
{{- end }}
