{{- if .Values.controller.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "controller.fullname" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: 7488
      protocol: TCP
  selector:
    {{- include "controller.selectorLabels" . | nindent 4 }}
{{- end }}