{{- if .Values.datastore.enabled -}}
{{- if .Values.datastore.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "datastore.serviceAccountName" . }}
  labels:
    {{- include "datastore.labels" . | nindent 4 }}
  {{- with .Values.datastore.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
