kind: Service
apiVersion: v1
metadata:
  name: {{ template "controller.fullname" . }}
  labels:
    app: {{ template "controller.name" . }}
    chart: {{ template "controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 8 }}
{{- end }}
spec:
  selector:
    app: {{ template "controller.name" . }}
    release: {{ .Release.Name }}
{{- if (or (eq .Values.service.type "ClusterIP") (empty .Values.service.type)) }}
  type: ClusterIP
{{- else }}
  type: {{ .Values.service.type }}
{{- end }}
  ports:
    - name: websocket
      protocol: TCP
      port: 7488
      targetPort: 7488
