name: publish-ci-test
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, edited, ready_for_review, synchronize]
    branches-ignore:
      - '*'
  push:
    branches-ignore:
      - '*'
      - '!master'
jobs:
  build-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Helm preinstalls ℹ️
        run: |
          echo '>> Prepare...'
          sudo mkdir -p /tmp/helm/bin
          sudo mkdir -p /tmp/helm/publish
          sudo apt update -y
          sudo apt install ca-certificates git openssh-server -y
          cd /tmp/helm/bin

      - name: Install helm 🚀
        uses: azure/setup-helm@v1
        with:
          version: '2.16.7'

      - name: Validate Charts ✅️
        run: |
          helm version -c
          helm init -c --stable-repo-url https://charts.helm.sh/stable
          sudo helm template charts/controller -f charts/controller/values.yaml
          sudo helm template charts/datastore -f charts/datastore/values.yaml

      - name: Pre Publish Charts ℹ️
        run: |
         sudo apt install jq curl -y
         echo $GITHUB_PAGES_REPO
         echo $GITHUB_BRANCH
         echo $GITHUB_ACTIONS_RUN_ID
         echo $GITHUB_ACTIONS_REPO
         sudo sh publish.sh $GITHUB_PAGES_REPO $GITHUB_BRANCH $GITHUB_USERNAME $GITHUB_ACTIONS_REPO $GITHUB_ACTIONS_RUN_ID $GITHUB_USERNAME_TOKEN
        env:
          GITHUB_PAGES_REPO: rookout/helm-charts
          GITHUB_BRANCH: ${{ github.ref }}
          GITHUB_USERNAME: ${{ secrets.SONARIO_GH_USER }}
          GITHUB_ACTIONS_REPO: ${{ github.repository }}
          GITHUB_ACTIONS_RUN_ID: ${{ github.run_id }}
          GITHUB_USERNAME_TOKEN: ${{ secrets.SONARIO_GH_TOKEN }}

      - name: Publish & Deploy Charts 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SONARIO_GH_TOKEN }}
          publish_dir: /tmp/helm/publish/helm-charts
          enable_jekyll: false
          keep_files: true
          user_name: "Github-Actions-CI"
          user_email: ${{env.GITHUB_USERNAME}}@users.noreply.github.com
          commit_message: Published by GitHub-Actions https://github.com/${{env.GITHUB_ACTIONS_REPO}}/actions/runs/${{env.GITHUB_ACTIONS_RUN_ID}}
        env:
          GITHUB_USERNAME: ${{ secrets.SONARIO_GH_USER }}
          GITHUB_ACTIONS_REPO: ${{ github.repository }}
          GITHUB_ACTIONS_RUN_ID: ${{ github.run_id }}

      - name: Verify - Published Charts ✅️
        run: |
          echo $GITHUB_BRANCH
          if [ "$GITHUB_BRANCH" = "refs/heads/master" ]; then
            echo "Waiting for repository to be updated before checking"
            sudo sleep 15
            helm repo add rookout https://helm-charts.rookout.com
            helm repo update
            helm repo list
            helm inspect chart rookout/controller
            helm inspect chart rookout/datastore
          fi
          echo $GITHUB_BRANCH
        env:
          GITHUB_BRANCH: ${{ github.ref }}
          
